"""Editable inventory tables (reservoir, acquisition, HP axes, eval sets) as an Excel workbook
(4 sheets) + CSVs for Google Sheets. Content from the July-16 sign-off tables + current code +
this-session findings. Each has a 'Notes / proposed change' column for remote editing.
-> ~/Downloads/pi_meeting_figs/editable_tables/
"""

import os
import pandas as pd

OUT = os.path.expanduser("~/Downloads/pi_meeting_figs/editable_tables")
os.makedirs(OUT, exist_ok=True)

# ---------------- 1. Reservoir strategies (July-16 2a implemented + 2b proposed/excluded) ----------------
reservoir = pd.DataFrame(
    [
        [
            "genomic",
            "—",
            "real held-out genomic MPRA sequences (the assay sequences themselves)",
            "real K562 MPRA",
            "chr-split; all D",
            "KEEP",
            "",
        ],
        [
            "random",
            "—",
            "each position i.i.d. uniform over A/C/G/T; 200 bp; no structure",
            "de novo",
            "uniform per position",
            "KEEP",
            "base control",
        ],
        [
            "motif_planted (FiNeMo)",
            "in-genomic-context; random-position",
            "FiNeMo-identify motifs in real seqs -> EXCISE motifs -> dinuc-shuffle the background -> RE-INSERT motifs (in genomic context, or random positions)",
            "real genomic",
            "FiNeMo hits; placement mode",
            "REVISE",
            "current motif-planting draws pushback; FiNeMo excise+shuffle+replace is defensible",
        ],
        [
            "dinuc_shuffle",
            "—",
            "shuffle each real seq preserving dinucleotide (2-mer) frequencies",
            "real K562 (shuffled)",
            "dinuc-preserving permutation",
            "KEEP",
            "SUBSUMES gc_matched",
        ],
        [
            "evoaug",
            "heavy, structural",
            "EvoAug perturbations: ins/del/sub/inversion/translocation/shift/noise",
            "real K562 (augmented)",
            "EXPOSE: n_augmentations, aug lengths, intensity",
            "PARAMETERIZE",
            "insert explicit augmentation params",
        ],
        [
            "partial_random_mutagenesis (PRM)",
            "prm_1/5/10/30pct",
            "mutate a fixed fraction of positions of a real genomic seq",
            "real (point-mutated)",
            "mutation_rate 0.01-0.30",
            "KEEP",
            "",
        ],
        [
            "phylogenetic (Zoonomia)",
            "cutoff: primates / mammals / all",
            "substitute at Zoonomia-conservation-matched per-position rates (real rates from Zoonomia CRE alignments)",
            "real genomic",
            "conservation cutoff (which best?)",
            "PARAMETERIZE",
            "Zoonomia alignments for ALL CREs — ask Anirban; pick cutoff",
        ],
        [
            "personal_variants (gnomAD)",
            "gnomAD (GTEx for testing)",
            "apply real human population variants (gnomAD) to genomic backgrounds",
            "real (population)",
            "variant source = gnomAD",
            "ADD",
            "wanted; own it; test on GTEx eQTLs",
        ],
        [
            "SNV / eQTL",
            "ref/alt pairs",
            "construct OUR OWN SNV / eQTL sequence set (control it, don't rely on others)",
            "real",
            "—",
            "PARTLY IMPLEMENTED",
            "SNV (point-mutation) path already exists in exp1_1_scaling; eQTL/GTEx is the NEW part",
        ],
        [
            "generative (GPA + uncond. diffusion)",
            "GPA (Anirban); unconditional diffusion",
            "Anirban's GPA (preferred over conditional diffusion) + unconditional diffusion; acquisition picks high-activity targets",
            "learned / de novo",
            "—",
            "PROPOSED",
            "GPA > conditional diffusion; InSilicoEvolutionGenerative partly exists",
        ],
        [
            "mixed_combination",
            "—",
            "scale each reservoir independently AND a combined MIX of all",
            "mix",
            "mixing ratio / acquisition-driven",
            "PARTLY IMPLEMENTED",
            "MixedPool + mixed_genomic_* configs exist; extend to a full all-reservoir mix",
        ],
        ["gc_matched", "—", "(removed)", "—", "—", "REMOVE", "dinuc_shuffle covers it"],
        [
            "in_silico_evolution",
            "—",
            "(removed)",
            "—",
            "—",
            "REMOVE",
            "let the acquisition function select high-activity instead",
        ],
        [
            "uncertainty_guided",
            "most_uncertain, balanced",
            "score base pool by oracle-ensemble variance",
            "real (re-scored)",
            "—",
            "DEPRIORITIZE",
            "per meeting",
        ],
        ["saliency-guided / Evo2-7B / GANs", "—", "—", "—", "—", "EXCLUDED", ""],
    ],
    columns=[
        "Family",
        "Subvariants",
        "Construction (algorithm)",
        "Background",
        "Key params",
        "Status",
        "Notes / proposed change",
    ],
)

# ---------------- 2. Acquisition strategies (July-16 3a/3b) ----------------
acquisition = pd.DataFrame(
    [
        [
            "random",
            "baseline",
            "—",
            "select the batch uniformly at random from reservoir candidates",
            "—",
            "IMPLEMENTED",
            "RandomAcquisition (verified in albench/acquisition/)",
        ],
        [
            "uncertainty",
            "uncertainty",
            "MC-dropout, ensemble variance",
            "score by student-ensemble disagreement (variance) or MC-dropout variance; take highest-variance batch",
            "n_mc=30 (dropout)",
            "IMPLEMENTED",
            "UncertaintyAcquisition (verified)",
        ],
        [
            "prior_knowledge",
            "biological prior",
            "weight config",
            "score by domain priors only (no model features): activity + motif-presence + GC priors",
            "w_act=0.5, w_motif=0.3, w_gc=0.2",
            "IMPLEMENTED",
            "PriorKnowledgeAcquisition (verified) — covers 'high-activity' via activity prior",
        ],
        [
            "ensemble_acq",
            "meta",
            "rule-set config",
            "aggregate scores across several acquisition rules",
            "hedge across rules",
            "IMPLEMENTED",
            "EnsembleAcquisition (verified)",
        ],
        [
            "diversity",
            "diversity",
            "LCMD (embedding), k-mer spectrum, motif diversity",
            "greedy farthest-point (LCMD) in student DNN-embedding space",
            "embed = student penultimate",
            "NOT IMPLEMENTED",
            "no acquisition class (only diversity_guided as a RESERVOIR)",
        ],
        [
            "badge",
            "uncert + diversity",
            "—",
            "k-means++ on loss-GRADIENT embeddings (magnitude=uncertainty, direction=diversity)",
            "grad wrt last layer",
            "NOT IMPLEMENTED",
            "to build",
        ],
        [
            "batchbald",
            "uncert + diversity",
            "—",
            "batch maximizing JOINT MI with model params (MC-dropout)",
            "n_mc_samples=30",
            "NOT IMPLEMENTED",
            "to build",
        ],
        [
            "bait",
            "uncert + diversity",
            "—",
            "Fisher-information batch selection (Fisher-optimal design)",
            "Fisher on last layer",
            "NOT IMPLEMENTED",
            "to build",
        ],
        [
            "combined",
            "weighted mix",
            "weights tunable",
            "weighted sum of uncertainty + diversity + activity-prior; alpha tunes",
            "w_unc, w_div, w_activity",
            "NOT IMPLEMENTED",
            "to build (needs diversity first)",
        ],
        [
            "expected_error_reduction",
            "EER",
            "—",
            "select sequences that most reduce expected test error",
            "—",
            "PROPOSED",
            "",
        ],
        [
            "annotation priors",
            "biological prior",
            "—",
            "annotation-based priors (function within the 200 bp window)",
            "—",
            "PROPOSED",
            "",
        ],
        [
            "broad scans",
            "scan",
            "motif + activity",
            "systematic broad motif + activity scans",
            "—",
            "PROPOSED",
            "",
        ],
    ],
    columns=[
        "Family",
        "Family type",
        "Subvariants",
        "Mechanism (algorithm)",
        "Key params",
        "Status",
        "Notes / proposed change",
    ],
)

# ---------------- 3. HP axes (PI-feedback ranges vs current code default) ----------------
hp = pd.DataFrame(
    [
        [
            "lr",
            "learning rate (OneCycle max)",
            "log-uniform 1e-5 – 1e-2",
            "1e-5 – 1e-2",
            "0.005",
            "CURRENT",
            "",
        ],
        ["batch_size", "minibatch size", "D-aware menu", "D-aware menu", "1024", "CURRENT", ""],
        ["n_layers", "conv blocks", "2 – 12", "2 – 12", "6", "CURRENT", ""],
        [
            "width_base",
            "base channel width",
            "64 – 512 (slope run used to 1024)",
            "16 – 256",
            "128",
            "PI-FEEDBACK (broaden)",
            "",
        ],
        [
            "width_jitter",
            "per-layer width multiplier",
            "0.5 – 2x (growing-with-depth)",
            "0.5 – 2x",
            "1.0",
            "CURRENT",
            "",
        ],
        [
            "ks (kernel size)",
            "conv kernel",
            "3,5,7,11,15,19,25",
            "3,5,7,9,11",
            "9",
            "PI-FEEDBACK (broaden)",
            "",
        ],
        [
            "block_class",
            "residual block type",
            "{eff, ag, plain}",
            "{eff, ag, plain}",
            "eff",
            "CURRENT",
            "",
        ],
        ["conv_dropout", "conv dropout", "0 – 0.5", "0 – 0.3", "0.1", "PI-FEEDBACK (broaden)", ""],
        ["dense_dropout", "head dropout", "0 – 0.5", "0 – 0.5", "0.1", "CURRENT", ""],
        [
            "weight_decay",
            "L2",
            "log-uniform 1e-8 – 1e-3",
            "1e-6 – 1e-1",
            "0.01",
            "PI-FEEDBACK (broaden)",
            "",
        ],
        [
            "optimizer",
            "optimizer",
            "{adam, adamw, muon}",
            "{adam, adamw, muon}",
            "adamw",
            "CURRENT",
            "",
        ],
        [
            "lr_schedule",
            "LR schedule",
            "plateau/onecycle/cosine/step/exp/const",
            "same",
            "onecycle",
            "CURRENT",
            "",
        ],
        ["lr_plateau_factor", "plateau decay", "{0.1, 0.2, 0.5}", "searchable", "—", "CURRENT", ""],
        ["pct_start", "OneCycle warmup frac", "{0.1,0.2,0.3,0.4}", "same", "0.3", "CURRENT", ""],
        [
            "shift_aug / shift_max",
            "random-shift augmentation",
            "on/off; {5,10,15,20}",
            "same",
            "on/10",
            "CURRENT",
            "",
        ],
        ["gradient_clip", "grad clipping", "none (fixed)", "none", "none", "CURRENT", ""],
        [
            "outer_skip_style / skip_stride",
            "skip connections",
            "{concat,add,none}; stride 1-4",
            "same",
            "concat",
            "CURRENT",
            "",
        ],
        [
            "NOVEL (nv1)",
            "off-menu axes",
            "activation{silu,relu,gelu,quickgelu,mish,elu}; loss{mse,huber,smoothl1}; se_reduction 2-16; reverse-complement; evoaug",
            "same (opt-in)",
            "—",
            "REVIEW",
            "",
        ],
    ],
    columns=[
        "Axis",
        "What it does",
        "Search range (PI-feedback)",
        "Current code default",
        "MPRA-LegNet default",
        "Status",
        "Notes / proposed change",
    ],
)

# ---------------- 4. Eval / test sets (battery construction) ----------------
evalsets = pd.DataFrame(
    [
        [
            "genomic",
            "in-distribution",
            "real held-out genomic sequences (the reference target)",
            "31,435",
            "",
        ],
        [
            "snv",
            "variant-effect",
            "SNV ref/alt pairs; scored on delta = alt - ref activity",
            "29,383",
            "",
        ],
        [
            "ood",
            "out-of-distribution",
            "high-activity DESIGNED sequences (off the genomic manifold)",
            "~22,000",
            "",
        ],
        [
            "dinuc_shuffle",
            "composition",
            "dinucleotide-preserving shuffle (Altschul-Erickson approx.)",
            "32,000",
            "",
        ],
        [
            "sub_low/med/high",
            "substitution",
            "5% / 20% / 50% of positions -> random A/C/G/T",
            "32,000 ea",
            "",
        ],
        [
            "ins_low/med/high",
            "insertion",
            "5% / 20% / 50% random bases inserted, re-cropped to 200 bp",
            "32,000 ea",
            "",
        ],
        [
            "del_low/med/high",
            "deletion",
            "5% / 20% / 50% of positions deleted, re-padded to 200 bp",
            "32,000 ea",
            "",
        ],
        [
            "translocation",
            "structural",
            "one large block swap (~50% of the sequence)",
            "32,000",
            "",
        ],
        ["inversion", "structural", "reverse of ~50% of the sequence", "32,000", ""],
        ["random_10k/32k", "random", "uniform random sequences (null baseline)", "10k / 32k", ""],
        ["ctrl_neg", "control", "control-negative sequences", "—", ""],
        [
            "eQTL (GTEx)",
            "variant interpretation",
            "real eQTL ref/alt pairs from GTEx (or other sources) — the application target",
            "TBD",
            "ADD — key application (variant interpretation); own it",
        ],
        [
            "per-strategy matched",
            "in-distribution generalization",
            "a held-out test set drawn from EACH reservoir strategy's own distribution",
            "TBD",
            "ADD — does a strategy generalize best on its own distribution, or is something surprising?",
        ],
    ],
    columns=[
        "Test set",
        "Regime",
        "Construction (chr-split held-out, oracle-labeled full856k_clean)",
        "n",
        "Notes / proposed change",
    ],
)

sheets = {"Reservoir": reservoir, "Acquisition": acquisition, "HP_axes": hp, "Eval_sets": evalsets}
xlsx = f"{OUT}/inventory_tables.xlsx"
with pd.ExcelWriter(xlsx, engine="openpyxl") as w:
    for name, df in sheets.items():
        df.to_excel(w, sheet_name=name, index=False)
        # widen columns
        ws = w.sheets[name]
        for i, col in enumerate(df.columns):
            width = min(60, max(14, int(df[col].astype(str).map(len).max() * 0.95) + 4))
            ws.column_dimensions[chr(65 + i)].width = width
for name, df in sheets.items():
    df.to_csv(f"{OUT}/{name.lower()}.csv", index=False)
print(f"WROTE {xlsx} (4 sheets) + 4 CSVs -> {OUT}")
for name, df in sheets.items():
    print(f"  {name}: {len(df)} rows")
